### ISSUE TITLE
Pluginname is different from controller name

### ISSUE THREAD

**Issue by Eumolp** [helhum/upload_example#16]
Hallo Helmut.
Just found your example. Thank you for that.
Installed it to see if there is something to see, and got an Error:

 #1316104317: The default controller for extension "UploadExample" and plugin "Piexample" can not be determined. Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php. (More information)

This is caused bay the PluginName 'Piexample' and the Controller named 'ExampleController.php' wich should be 'PIeexampleController.php' in this case. Al least now it throws no error.

Af course this is only a example, but for beginners like me it makes things not easyer if you start with errorcodes.

Nevertheless, thank you for sharing this fileuploadExample.

Christian.

**Comment by helhum** [comment]
Sorry, I don't understand your problem here at all. Installing the extension works without errors. Renaming of the controller is just wrong...
