### ISSUE TITLE
Reference counter not updated?

### ISSUE THREAD

**Issue by bplusd-interactive** [helhum/upload_example#18]
Hi,

When uploading, the file is created in the filesystem and associated with the model - I can validate this by opening the object in the List view.

Unfortunately the reference counter doesn't seem to be updated - when I open the image properties no references are shown. When I open the object (using editor in Typoe backend) and save it, reference counter is updated.

Is there any way to update/refresh the reference counter for the newly uploaded image?

Kind regards,
Carsten

**Comment by helhum** [comment]
Can you try setting `config.tx_extbase.persistence.updateReferenceIndex = 1`

Maybe this would be enough already
