### ISSUE TITLE
#1365429656: TYPO3 Fatal Error: Extension key "upload_example" is NOT loaded! 

### ISSUE THREAD

**Issue by Geddo** [helhum/upload_example#19]
Fresh TYPO3 6.2.12 installation, installing extension via Extension-Manager -> Fatal Error. What I'm missing?

**Comment by helhum** [comment]
I have no idea how you get to this point. How do you install the extension? Did you clone the repo into typo3conf/ext?

**Comment by Geddo** [comment]
exactly. Download the zip from github, copy it to typo3conf/ext, install it via extension manager -> Crash.

**Comment by helhum** [comment]
And you are sure the extension folder is named `typo3conf/ext/upload_example` and this folder contains the ext_emconf.php file?

**Comment by Geddo** [comment]
Just tried it with a fresh 6.2.13 - works. Strange. Sorry for the trouble. WORKS!
