### ISSUE TITLE
After Update TYPO3 6.2.5 -> 6.2.15 property-mapping problem when more than one image-upload-fields

### ISSUE THREAD

**Issue by wrock** [helhum/upload_example#21]
#1297759968: Exception while property mapping at property path "":PHP Catchable Fatal Error: Argument 1 passed to Rockit\Dreams\Domain\Model\Project::setImageone() must be an instance of TYPO3\CMS\Extbase\Domain\Model\FileReference, null given, called in /Users/Shared/vhosts/common/typo3_src-6.2.15/typo3/sysext/extbase/Classes/Reflection/ObjectAccess.php on line 200 and defined in /Users/Shared/vhosts/dreams.eu/httpdocs/typo3conf/ext/dreams/Classes/Domain/Model/Project.php line 431

**Comment by helhum** [comment]
Well, depends how your Project Domain model looks like.
Nothing to be changed here in this repo, no bug in the example code
