### ISSUE TITLE
Exception while property mapping at property path... The identity property "..." is no UID.

### ISSUE THREAD

**Issue by andreaspot** [helhum/upload_example#24]
I try to use this example to load some pdf files in a typo3 backend module (registerModule...), but when i try upload a file i get this error message:
"Exception while property mapping at property path "file": The identity property "myfile.pdf" is no UID"
Do you know something about it? The error may occur due to the fact that I'm using this code in a backend module? Maybe the configurations of file "ext_typoscript_setup.txt" in the backend module are not interpreted?
For your information i'm using Typo3 CMS 7.6.9.
Thank you much.

**Comment by helhum** [comment]
I'm sorry, this bugtracker isn't a support platform. If you found a bug in the code of this extension, e.g. it throws an exception, when installing it and uploading files within the given functionality, I'll try to help.

Other than that, please head over to http://forum.typo3.org or https://forger.typo3.org/slack and ask for help in the according channels.

> I try to use this example to load some pdf files in a typo3 backend module (registerModule...), but when i try upload a file i get this error message

No, out of the top of my head I don't know what the issue could be. Without seeing any code, it also might be difficult for others to help.

**Comment by slowhand11** [comment]
Had same error. i figured out that enctype="multipart/form-data" in my opening <f:form is missing.
