### ISSUE TITLE
"Ref." column in Filelist is not counting up in TYPO3 8.7.19

### ISSUE THREAD

**Issue by markustobler** [helhum/upload_example#34]
I tested the example with my own model in TYPO3 8.7.19. Everything works fine except the "Ref." column in Filelist has no Reference. Does anybody now what could be the problem?

![filelist](https://user-images.githubusercontent.com/4266664/46003937-f8c1e080-c0b1-11e8-98bb-dca8eda1dafe.jpg)

**Comment by Kitzberger** [comment]
If I’m not completely off here, i think that column got refactored in 8.7 and doesn’t show the number at all anymore...

**Comment by markustobler** [comment]
The number appears after I open the data record in the backend and click save.

If that Example is not working anymore for TYPO3 8.7 what approach would you recommend for saving images in the frontend? Even the official TYPO3 documentation links to this repository.

**Comment by helhum** [comment]
@markustobler 

The reference index is never updated by default when creating records via Extbase in the frontend.

You can try setting `config.tx_extbase.persistence.updateReferenceIndex = 1` and see if this helps.

Other than that, you could schedule updating the reference index, which then should pick up references created by Extbase

**Comment by markustobler** [comment]
> @markustobler
> 
> The reference index is never updated by default when creating records via Extbase in the frontend.
> 
> You can try setting `config.tx_extbase.persistence.updateReferenceIndex = 1` and see if this helps.
> 
> Other than that, you could schedule updating the reference index, which then should pick up references created by Extbase

**Comment by markustobler** [comment]
@helhum Thank you for your help it worked perfect 🎉
