### ISSUE TITLE
Problems with imageCollections and "cascade remove"

### ISSUE THREAD

**Issue by ThomasRo** [helhum/upload_example#5]
If you use an image collection und your model for the collection is configured as "cascade remove", the assigned images will get lost as soon as you edit an existing data set and save without any changes.

**Comment by sgrossberndt** [comment]
See https://forum.typo3.org/index.php?t=msg&th=196895&goto=685918&#msg_685918

**Comment by helhum** [comment]
Ok, so this needs to be fixed in TYPO3
